export default {
  docs: [
    {
      title: '开始',
      type: 'document', // 普通文档
      children: [
        {
          title: '说明',
          name: 'readme',
          meta: { docType: 'explain' },
          path: '/vue-mobile/components/readme',
          component: () => import('@/../README.md'),
        },
        {
          title: '贡献指南',
          name: 'contributing',
          meta: { docType: 'explain' },
          path: '/vue-mobile/components/contributing',
          component: () => import('@/../CONTRIBUTING.md'),
        },
        {
          title: '更新日志',
          name: 'changelog',
          meta: { docType: 'explain' },
          path: '/vue-mobile/components/changelog',
          component: () => import('@/../CHANGELOG.md'),
        },
      ],
    },
    {
      title: '基础组件',
      type: 'component', // 组件文档
      children: [
        {
          title: 'Button 按钮',
          name: 'button',
          meta: { docType: 'base' },
          path: '/vue-mobile/components/button',
          component: () => import('@/button/button.md'),
        },
        {
          title: 'Divider 分割符',
          name: 'divider',
          meta: { docType: 'base' },
          path: '/vue-mobile/components/divider',
          component: () => import('@/divider/divider.md'),
        },
        {
          title: 'Icon 图标',
          name: 'icon',
          meta: { docType: 'base' },
          path: '/vue-mobile/components/icon',
          component: () => import('@/icon/icon.md'),
        }
      ],
    },
    {
      title: '信息展示',
      type: 'component',
      children: [
        {
          title: 'Badge 徽标',
          name: 'badge',
          meta: { docType: 'data' },
          path: '/vue-mobile/components/badge',
          component: () => import('@/badge/badge.md'),
        },
        {
          title: 'Tag 标签',
          name: 'tag',
          meta: { docType: 'data' },
          path: '/vue-mobile/components/tag',
          component: () => import('@/tag/tag.md'),
        },
        {
          title: 'DropdownMenu 下拉菜单',
          name: 'dropdown-menu',
          meta: { docType: 'data' },
          path: '/vue-mobile/components/dropdown-menu',
          component: () => import('@/dropdown-menu/dropdown-menu.md'),
        },
        {
          title: 'Collapse 折叠面板',
          name: 'collapse',
          meta: { docType: 'data' },
          path: '/vue-mobile/components/collapse',
          component: () => import('@/collapse/collapse.md'),
        },
        {
          title: 'Cell 单元格',
          name: 'cell',
          meta: { docType: 'data' },
          path: '/vue-mobile/components/cell',
          component: () => import('@/cell/cell.md'),
        },
        {
          title: 'Swiper 轮播',
          name: 'swiper',
          meta: { docType: 'data' },
          path: '/vue-mobile/components/swiper',
          component: () => import('@/swiper/swiper.md'),
        }
      ],
    },
    {
      title: '输入类组件',
      type: 'component',
      children: [
        {
          title: 'Stepper 步进器',
          name: 'stepper',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/stepper',
          component: () => import('@/stepper/stepper.md'),
        },
        {
          title: 'Slider 滑动选择器',
          name: 'slider',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/slider',
          component: () => import('@/slider/slider.md'),
        },
        {
          title: 'Picker 选择器',
          name: 'picker',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/picker',
          component: () => import('@/picker/picker.md'),
        },
        {
          title: 'Radio 单选框',
          name: 'radio',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/radio',
          component: () => import('@/radio/radio.md'),
        },
        {
          title: 'Rate 评分',
          name: 'rate',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/rate',
          component: () => import('@/rate/rate.md'),
        },
        {
          title: 'Switch 开关',
          name: 'switch',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/switch',
          component: () => import('@/switch/switch.md'),
        },
        {
          title: 'CheckBox 复选框',
          name: 'checkbox',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/checkbox',
          component: () => import('@/checkbox/checkbox.md'),
        },
        {
          title: 'Input 输入框',
          name: 'input',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/input',
          component: () => import('@/input/input.md'),
        },
        {
          title: 'Fab 悬浮按钮',
          name: 'fab',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/fab',
          component: () => import('@/fab/fab.md'),
        },
        {
          title: 'SearchField 搜索框',
          name: 'search-field',
          meta: { docType: 'form' },
          path: '/vue-mobile/components/search-field',
          component: () => import('@/search-field/search-field.md'),
        },
      ],
    },
    {
      title: '导航组件',
      type: 'component',
      children: [
        {
          title: 'Steps 步骤条',
          name: 'steps',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/steps',
          component: () => import('@/steps/steps.md'),
        },
        {
          title: 'TabBar 标签栏',
          name: 'tabbar',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/tabbar',
          component: () => import('@/tab-bar/tab-bar.md'),
        },
        {
          title: 'SegmentedControl 分段器',
          name: 'segmented-control',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/segmented-control',
          component: () => import('@/segmented-control/segmented-control.md'),
        },
        {
          title: 'Preview 图片预览',
          name: 'preview',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/preview',
          component: () => import('@/preview/preview.md'),
        },
        {
          title: 'Drawer 抽屉',
          name: 'drawer',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/drawer',
          component: () => import('@/drawer/drawer.md'),
        },
        {
          title: 'Tabs 选项卡',
          name: 'tabs',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/tabs',
          component: () => import('@/tabs/tabs.md'),
        },
        {
          title: 'Navbar 导航条',
          name: 'navbar',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/navbar',
          component: () => import('@/navbar/navbar.md'),
        },
        {
          title: 'Indexes 索引',
          name: 'indexes',
          meta: { docType: 'navigation' },
          path: '/vue-mobile/components/indexes',
          component: () => import('@/indexes/indexes.md'),
        },
      ],
    },
    {
      title: '消息提醒',
      type: 'component', // 组件文档
      children: [
        {
          title: 'Progress 进度条',
          name: 'progress',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/progress',
          component: () => import('@/progress/progress.md'),
        },
        {
          title: 'ActionSheet 动作面板',
          name: 'actionsheet',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/actionsheet',
          component: () => import('@/action-sheet/action-sheet.md'),
        },
        {
          title: 'Toast 轻提示',
          name: 'toast',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/toast',
          component: () => import('@/toast/toast.md'),
        },
        {
          title: 'Message 消息',
          name: 'message',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/message',
          component: () => import('@/message/message.md'),
        },
        {
          title: 'NoticeBar 公告栏',
          name: 'notice-bar',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/notice-bar',
          component: () => import('@/notice-bar/notice-bar.md'),
        },
        {
          title: 'Dialog 弹出框',
          name: 'dialog',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/dialog',
          component: () => import('@/dialog/dialog.md'),
        },
        {
          title: 'Popup 弹出层',
          name: 'popup',
          meta: { docType: 'message' },
          path: '/vue-mobile/components/popup',
          component: () => import('@/popup/popup.md'),
        },
      ],
    },
  ],
};
