/**
 * 该文件为脚本自动生成文件，请勿随意修改。如需修改请联系 PMC
 * https://github.com/TDesignOteam/tdesign-api
 * eslint-disable
 * */
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TActionSheet: typeof import('tdesign-mobile-vue')['ActionSheet'];
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar'];
    TAvatarGroup: typeof import('tdesign-mobile-vue')['AvatarGroup'];
    TBackTop: typeof import('tdesign-mobile-vue')['BackTop'];
    TBadge: typeof import('tdesign-mobile-vue')['Badge'];
    TBaseTable: typeof import('tdesign-mobile-vue')['BaseTable'];
    TButton: typeof import('tdesign-mobile-vue')['Button'];
    TCalendar: typeof import('tdesign-mobile-vue')['Calendar'];
    TCascader: typeof import('tdesign-mobile-vue')['Cascader'];
    TCell: typeof import('tdesign-mobile-vue')['Cell'];
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup'];
    TCheckTag: typeof import('tdesign-mobile-vue')['CheckTag'];
    TCheckTagGroup: typeof import('tdesign-mobile-vue')['CheckTagGroup'];
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox'];
    TCheckboxGroup: typeof import('tdesign-mobile-vue')['CheckboxGroup'];
    TCol: typeof import('tdesign-mobile-vue')['Col'];
    TCollapse: typeof import('tdesign-mobile-vue')['Collapse'];
    TCollapsePanel: typeof import('tdesign-mobile-vue')['CollapsePanel'];
    TColorPicker: typeof import('tdesign-mobile-vue')['ColorPicker'];
    TComment: typeof import('tdesign-mobile-vue')['Comment'];
    TCountDown: typeof import('tdesign-mobile-vue')['CountDown'];
    TDateRangePicker: typeof import('tdesign-mobile-vue')['DateRangePicker'];
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker'];
    TDialog: typeof import('tdesign-mobile-vue')['Dialog'];
    TDivider: typeof import('tdesign-mobile-vue')['Divider'];
    TDrawer: typeof import('tdesign-mobile-vue')['Drawer'];
    TDropdownItem: typeof import('tdesign-mobile-vue')['DropdownItem'];
    TDropdownMenu: typeof import('tdesign-mobile-vue')['DropdownMenu'];
    TEmpty: typeof import('tdesign-mobile-vue')['Empty'];
    TFab: typeof import('tdesign-mobile-vue')['Fab'];
    TFooter: typeof import('tdesign-mobile-vue')['Footer'];
    TForm: typeof import('tdesign-mobile-vue')['Form'];
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem'];
    TGrid: typeof import('tdesign-mobile-vue')['Grid'];
    TGridItem: typeof import('tdesign-mobile-vue')['GridItem'];
    TIconSVG: typeof import('tdesign-mobile-vue')['IconSVG'];
    TIconfont: typeof import('tdesign-mobile-vue')['Iconfont'];
    TImage: typeof import('tdesign-mobile-vue')['Image'];
    TImageViewer: typeof import('tdesign-mobile-vue')['ImageViewer'];
    TIndexes: typeof import('tdesign-mobile-vue')['Indexes'];
    TIndexesAnchor: typeof import('tdesign-mobile-vue')['IndexesAnchor'];
    TInput: typeof import('tdesign-mobile-vue')['Input'];
    TInputAdornment: typeof import('tdesign-mobile-vue')['InputAdornment'];
    TLink: typeof import('tdesign-mobile-vue')['Link'];
    TList: typeof import('tdesign-mobile-vue')['List'];
    TLoading: typeof import('tdesign-mobile-vue')['Loading'];
    TMessage: typeof import('tdesign-mobile-vue')['Message'];
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar'];
    TNoticeBar: typeof import('tdesign-mobile-vue')['NoticeBar'];
    TOverlay: typeof import('tdesign-mobile-vue')['Overlay'];
    TPagination: typeof import('tdesign-mobile-vue')['Pagination'];
    TPicker: typeof import('tdesign-mobile-vue')['Picker'];
    TPickerItem: typeof import('tdesign-mobile-vue')['PickerItem'];
    TPopconfirm: typeof import('tdesign-mobile-vue')['Popconfirm'];
    TPopover: typeof import('tdesign-mobile-vue')['Popover'];
    TPopup: typeof import('tdesign-mobile-vue')['Popup'];
    TPrimaryTable: typeof import('tdesign-mobile-vue')['PrimaryTable'];
    TProgress: typeof import('tdesign-mobile-vue')['Progress'];
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh'];
    TRadio: typeof import('tdesign-mobile-vue')['Radio'];
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup'];
    TRangeInput: typeof import('tdesign-mobile-vue')['RangeInput'];
    TRangeInputPopup: typeof import('tdesign-mobile-vue')['RangeInputPopup'];
    TRate: typeof import('tdesign-mobile-vue')['Rate'];
    TResult: typeof import('tdesign-mobile-vue')['Result'];
    TRow: typeof import('tdesign-mobile-vue')['Row'];
    TSearch: typeof import('tdesign-mobile-vue')['Search'];
    TSegmentedControl: typeof import('tdesign-mobile-vue')['SegmentedControl'];
    TSelect: typeof import('tdesign-mobile-vue')['Select'];
    TSideBar: typeof import('tdesign-mobile-vue')['SideBar'];
    TSideBarItem: typeof import('tdesign-mobile-vue')['SideBarItem'];
    TSkeleton: typeof import('tdesign-mobile-vue')['Skeleton'];
    TSlider: typeof import('tdesign-mobile-vue')['Slider'];
    TSpace: typeof import('tdesign-mobile-vue')['Space'];
    TStatistic: typeof import('tdesign-mobile-vue')['Statistic'];
    TStepItem: typeof import('tdesign-mobile-vue')['StepItem'];
    TStepper: typeof import('tdesign-mobile-vue')['Stepper'];
    TSteps: typeof import('tdesign-mobile-vue')['Steps'];
    TSticky: typeof import('tdesign-mobile-vue')['Sticky'];
    TStickyTool: typeof import('tdesign-mobile-vue')['StickyTool'];
    TSwipeCell: typeof import('tdesign-mobile-vue')['SwipeCell'];
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper'];
    TSwiperNav: typeof import('tdesign-mobile-vue')['SwiperNav'];
    TSwitch: typeof import('tdesign-mobile-vue')['Switch'];
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar'];
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem'];
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel'];
    TTabs: typeof import('tdesign-mobile-vue')['Tabs'];
    TTag: typeof import('tdesign-mobile-vue')['Tag'];
    TTextarea: typeof import('tdesign-mobile-vue')['Textarea'];
    TTimeRangePicker: typeof import('tdesign-mobile-vue')['TimeRangePicker'];
    TTimeline: typeof import('tdesign-mobile-vue')['Timeline'];
    TTimelineItem: typeof import('tdesign-mobile-vue')['TimelineItem'];
    TToast: typeof import('tdesign-mobile-vue')['Toast'];
    TTooltip: typeof import('tdesign-mobile-vue')['Tooltip'];
    TTreeSelect: typeof import('tdesign-mobile-vue')['TreeSelect'];
    TUpload: typeof import('tdesign-mobile-vue')['Upload'];
    TWatermark: typeof import('tdesign-mobile-vue')['Watermark'];
  }
}

export {};
