name: Publish_Any_Commit
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    if: ${{ github.repository == 'Tencent/tdesign-mobile-vue' && !startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install

      - run: npm run build

      - run: |
          mkdir templates && cd templates
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main mobile-vue-vite --template mobile-vue-vite
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main mobile-vue-vite-on-demand --template mobile-vue-vite-on-demand
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main mobile-vue-tsx-vite --template mobile-vue-tsx-vite
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main mobile-vue-tsx-rspack --template mobile-vue-tsx-rspack
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main mobile-vue-rspack --template mobile-vue-rspack
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main mobile-vue-rspack-on-demand --template mobile-vue-rspack-on-demand

      - run: npx pkg-pr-new publish --template './templates/*'
