# 文件名建议统一为 tag-push.yml
# 应用 publish.yml 的 demo

name: TAG_PUSH

on: create

jobs:
  call-publish:
    if: github.event.ref_type == 'tag'
    uses: TDesignOteam/workflows/.github/workflows/reusable-publish-npm.yml@main
    with:
      node-version-file: .node-version
      token: ${{ secrets.PERSONAL_TOKEN }}
      surge-token: ${{ secrets.TDESIGN_SURGE_TOKEN }}
    permissions:
      contents: read
      id-token: write
