[default.extend-words]
actived = "actived"
formated = "formated"
formate = "formate"
Colum = "Colum"
ans = "ans"
ba = "ba"
ded = "ded"
Hel = "Hel"
Successivo = "Successivo"

[files]
extend-exclude = ["CHANGELOG.md", "*.snap"]
